import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from '../context/UserContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rey Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div className="flex flex-col md:flex-row min-h-screen">
            <Sidebar />
            <div className="flex-1 md:ml-60 max-w-3xl mx-auto pl-20 flex flex-col justify-center items-center">
              <div className="mt-8 w-full">{children}</div>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}